[project]
name = "spotifyify"
version = "0.4.0"
description = "Async wrapper for spotipy with a focus on integration with MCP agents."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.0",
    "pydantic>=2.12.0",
    "pydantic-settings>=2.12.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0,<26",
    "pytest>=8.4.1,<9",
    "pytest-asyncio>=1.1.0,<2",
    "pytest-mock>=3.14.1,<4",
    "pytest-cov>=6.2.1,<7",
    "isort>=6.0.1,<7",
    "ruff>=0.13.1",
    "pre-commit>=4.3.0",
]

[build-system]
requires = ["setuptools>=75.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["spotifyify*"]

[tool.uv]
package = true
